### ISSUE TITLE
New users get default space assigned

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold#220]
Hi,

we currently use 
> Scoold Pro
Scoold version: 1.41.2
Production mode: true
Para app: app:scoold
Para version: 1.38.4
Para endpoint: http://localhost:8080

With following configuration

> auto_assign_spaces: comlet
> is_default_space_public: false

Users get authenticated via LDAP.

When new users log in they get assigned comlet **and** default space. The latter should not be the case with our configuration. At least it was not the case in the previous version of Scoold Pro that ran on our productive system.

Best regards,
Björn

**Comment by albogdano** [comment]
Thanks for the bug report, Björn! I just fixed this. There is an undocumented (now added to the README) option which should fix your problem immediately available in 1.41.2 as well:
```
para.reset_spaces_on_new_assignment = true
```

**Comment by b-morgenthaler** [comment]
Unfortunately, this option does not help. New users still get "default" space assigned.
Anything else to do than adding the option to scoold's config and restart scoold service?

**Comment by albogdano** [comment]
You were right, that didn't work as expected. Now it's actually fixed in master. Expect a new release soon.
